# Generated by Django 5.1.4 on 2024-12-22 02:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='car make model',
                                          max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='online course',
                                          max_length=30)),
                ('Type', models.CharField(choices=[
                 ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Wagon', 'Wagon')],
                                          default='Sedan', max_length=20)),
                ('year', models.IntegerField(default=2015, validators=[
                 django.core.validators.MinValueValidator(2015),
                 django.core.validators.MaxValueValidator(2023)])),
                ('car_make', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='djangoapp.carmake')),
            ],
        ),
    ]
